### ISSUE TITLE
Could not find this gem

### ISSUE THREAD

**Issue by ykyk1218** [mackerelio/itamae-plugin-recipe-mackerel-agent#2]
I write gem 'itamae-plugin-recipe-mackerel-agent' into Gemfile and execute command  `bundle install`
But displayed following error message

```
Could not find gem 'itamae-plugin-recipe-mackerel-agent (>= 0) ruby' in any of the gem sources listed in your Gemfile or available on
this machine.
```

Do not publish from now on as Gemfile？

**Comment by takahashim** [comment]
https://mackerel.io/ja/blog/entry/weekly/20161104
Congrats! 👏

**Comment by astj** [comment]
Thank you for your feedback!
As takahashim-san mentioned, we published to RubyGems. Now `gem install 'itamae-plugin-recipe-mackerel-agent'` (or `bundle install` with such Gemfile) will success.
